### ISSUE TITLE
[Bug] driver.get_rect 方法会报错

### ISSUE THREAD

**Issue by mocobk** [SonicCloudOrg/sonic-uiautomator2-python-client#6]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.1

### Deploy platform

Macosx

### Minimal reproduce step

![image](https://github.com/SonicCloudOrg/sonic-uiautomator2-python-client/assets/26194964/9f509054-0871-4105-954e-e3402724c3b2)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
欢迎发起pr贡献噢~ 近期我们暂时在做别的

**Comment by mocobk** [comment]
> 欢迎发起pr贡献噢~ 近期我们暂时在做别的

好的

**Comment by mocobk** [comment]
已修复： https://github.com/SonicCloudOrg/sonic-uiautomator2-python-client/pull/8

**Comment by ZhouYixun** [comment]
感谢
