### ISSUE TITLE
[Feat] 请问 uiautomator2-client 有 node 版本计划吗 

### ISSUE THREAD

**Issue by mocobk** [SonicCloudOrg/sonic-uiautomator2-python-client#9]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.1

### Deploy platform

Macosx

### Minimal reproduce step

当前项目中有需求使用 node js 进行真机自动化调度，希望能有一个 node 版本，我也可以参与共建

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
https://github.com/appium/appium-uiautomator2-driver

如果你有研究过appium的话，你会发现appium的driver本来就是node

**Comment by mocobk** [comment]
> https://github.com/appium/appium-uiautomator2-driver
> 
> 如果你有研究过appium的话，你会发现appium的driver本来就是node
好的，感谢大佬指点，我去研究下
